### ISSUE TITLE
[Bug] It's not Smart or Intelligent

### ISSUE THREAD

**Issue by DrZed** [wiggle10000/smartai#2]
This AI Being created by wiggle? Feh, it probably won't be intelligent enough to tie a virtual shoelace, but it's definately artificial so you have 1/7th of the github repo name correct...

**Comment by MFernflower** [comment]
https://www.youtube.com/watch?v=RMdmPZ4Xk1w

**Comment by wiggle10000** [comment]
Non-constructive criticism is unwelcome here.. please do not do that.

**Comment by DrZed** [comment]
As for will you be able to make an AI? No, you don't have the computing power, intelligence, or resources to make an AI Especially with your "neural networking" Since it's a bogus term in your use.if you want to work on an AI Join facebook they've already made it pretty far into the AI trade with 'M'

**Comment by DrZed** [comment]
Now that I remember correctly, You're wiggle the one in my contacts all my other contacts make fun of... Why you ask? Because you have hundreds of projects you've had for years and not a dammed one will ever get finished, and you rip code off of others most of the dammed time... You might as well call this Project Hankenstein before it's ready..
